In [33]:
import numpy as np

In [34]:
MAX_PLAYERS = 18
MAX_CARD_ORDINALITY = 18
MAX_CARD_NUMBER = 18

In [43]:
file_path = "network_input_example.bin"

# now read the file back into a numpy array
example_output = np.fromfile(file_path, dtype=np.uint8)
len(example_output)

746

In [42]:
array = np.random.random((1))
print(array)
print(array.dtype)
print(array.dtype.byteorder)
print([int(b) for b in array.tobytes()])

[0.72129163]
float64
=
[18, 6, 6, 46, 210, 20, 231, 63]


In [44]:
# 1. Card matrix of player hand
read_start = 0
read_end = MAX_CARD_ORDINALITY * MAX_CARD_NUMBER
card_matrix = example_output[read_start:read_end].reshape(MAX_CARD_ORDINALITY, MAX_CARD_NUMBER)
print("Card matrix of player hand")
print(card_matrix)
# 2. Card matrix of opponent hands
read_start = read_end
read_end += MAX_CARD_ORDINALITY * MAX_CARD_NUMBER
card_matrix = example_output[read_start:read_end].reshape(MAX_CARD_ORDINALITY, MAX_CARD_NUMBER)
print("Card matrix of opponent hands")
print(card_matrix)
# 3. Whether there is a set in play
read_start = read_end
read_end += 1
print("Whether there is a set in play")
print(example_output[read_start])
# 4. One-hot encoding of the rank of the set in play
read_start = read_end
read_end += MAX_CARD_ORDINALITY
print("One-hot encoding of the rank of the set in play")
print(example_output[read_start:read_end])
# 5. One-hot encoding of the number of the set in play
read_start = read_end
read_end += MAX_CARD_NUMBER - 1
print("One-hot encoding of the number of the set in play")
print(example_output[read_start:read_end])
# 6. One-hot encoding of the the current trick leader
read_start = read_end
read_end += MAX_PLAYERS
print("One-hot encoding of the the current trick leader")
print(example_output[read_start:read_end])
# 7. Encoding of the players who have passed
read_start = read_end
read_end += MAX_PLAYERS
print("Encoding of the players who have passed")
print(example_output[read_start:read_end])
# 8. Hand sizes of the players
read_start = read_end
read_end += MAX_PLAYERS
print("Hand sizes of the players")
print(example_output[read_start:read_end])
print("Value")
print(example_output[read_end:read_end+8])

Card matrix of player hand
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Card matrix of opponent hands
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 

In [45]:
# Convert value to float
value = np.frombuffer(example_output[read_end:read_end+8], dtype=np.float64)[0]
print("Value")
print(value)

Value
0.72129163
